credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: "$2b$12$kBkSKFEARN1PPqJ28KE6D.WbovJmqxaNKvMu4tFujNI8inehfeDhW" # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: "$2b$12$Tyx5su0Q/XcTcf9gZd3bzuVkaxpj9degimpSuxcvveyrPNzyvG60i" # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - muhammad.ridwan@majoo.id