from matplotlib.pyplot import text
import streamlit as st
from PIL import Image





# authentication
# streamlit_app.py

import streamlit as st


# streamlit_app.py

import streamlit as st


def check_password():
    """Returns `True` if the user had the correct password."""
    @st.cache(ttl=60*60, suppress_st_warning=True)
    def password_entered():
        """Checks whether a password entered by the user is correct."""
        if st.session_state["password"] == st.secrets["password"]:
            st.session_state["password_correct"] = True
            # del st.session_state["password"]  # don't store password
        else:
            st.session_state["password_correct"] = False

    if "password_correct" not in st.session_state:
        # First run, show input for password.
        st.text_input(
            "Password", type="password", on_change=password_entered, key="password"
        )
        return False
    elif not st.session_state["password_correct"]:
        # Password not correct, show input + error.
        st.text_input(
            "Password", type="password", on_change=password_entered, key="password"
        )
        st.error("😕 Password incorrect")
        return False
    else:
        # Password correct.
        return True

if check_password():


    def run():
        # favicon image
        im = Image.open("favicon.ico")

        st.set_page_config(
            page_title="Marketing Intelligence Dashboard",
            page_icon=im,
        )

        st.write("# Welcome to Marketing Intelligence Dashboard! 🕵️‍♂️")

        st.sidebar.success("Select a page above")

        st.markdown(
            """
            ### Overview
            Marketing intelligence is a field of business data that generated by collecting industrial-related business insights.
            It includes competitor, trends, technology and other related information.
            **👈 Select a from the sidebar** to see further analytical insights
            ### Sources of Data
            We are working to add more data in the future so we can gather the insightful information from this dashboard. But for this 
            developoment, we have collected several data below 
            - __Ads Library__
            Data from this source is gathered using scraping tools to fetch our and competitor's campaigns running on Meta inc platform (Facebook, Instagram). To update the data, we need to manually scrap whenever we need to. (e.g: weekly)
            - __Social Media__
            By fetching instagram's profiles of our competitors via Graph API, we gain insight about their engagement on Instagram platform. The data shown is real time and updated automatically in daily basis. But for limitation and following instagram's rules, we just can fetch data for the last 2 weeks and data is delayed up to 48 hours.
            - __E-commerce__
            Until now, we've gathered competitor's official account on Tokopedia only where they run promotional sales programs regularly, so we can analyze what are best products/services they've sold and in which prices. Similar to Ads Library data, we need to update it regularly using scraping tools (e.g: weekly)
            
        """
        )


    if __name__ == "__main__":
        run()

